#!/usr/bin/expect --
# =====================================================================
# Expect script that executes mss_cleansp
# =====================================================================
# HISTORY:
# 9-09-2015 Ilya
# 5-26-2016 replace TelnetLogin with Candy's SshLogIn for Unix Only
#
# =========================================================================================================================
#

# set timeout -1

source $env(AUTO_EXPECT_DIR)/NetLib.exp

global UNIX_TRUE UNIX_FALSE OS WINDOWS

set Stat $UNIX_TRUE
set Plat $env(PLATFORM)

SetEnv $env(this_vardir)
# Login to host with ssh 

set timeout 500

# DO UNIX STUFF
if { [ string compare "$Plat" "$WINDOWS" ] == 0 } {
   spawn telnet $env(this_hostname)
} else {
   if [regexp {.*AIX.*} $OS ] {
      spawn telnet $env(this_hostname)
   } else {
      spawn ssh -l $env(this_spadmin) $env(this_hostname)
   }
}
LogInToHost $env(this_spadmin) $env(this_spapass)
    # move core files to vardir because ora_clean will delete them
    send "mv $env(this_vardir)/dump/* $env(this_vardir)\r"
    expect "#"

    # get ready to run td_cleansp
    send "cd $env(this_proddir)/bin\r"
    expect "#"

    # run td_cleansp
    send "./td_cleansp sp_td/$env(this_ora_spadmin)/$env(this_ora_spapass)\r"

    while 1 {
        expect {
            "#"      { break }
            " : "   { send "y\r" }
            timeout { puts "Timedout running td_cleansp"; set Stat $UNIX_FALSE }
        }
    }


# dump buffer to log
set LogFile $env(AUTO_TEST_CASE_LOG)
set Log [open $LogFile a]
puts $Log $expect_out(buffer)
close $Log

#close session
send "exit\r"
expect EOF
exit $Stat
