--for postgresql
--dzhu, 7/28/2016
DROP TABLE IF EXISTS sp_pg.QA_TIMESTAMP;

CREATE TABLE sp_pg.QA_TIMESTAMP
(
--  COL_NUMBER       NUMBER(25,2),
  COL_NUMBER       NUMERIC(25,2),
  COL_TIMESTAMP1   TIMESTAMP(4),
  COL_TIMESTAMP2   TIMESTAMP,
  COL_TIMESTAMP3   TIMESTAMP(3),
  COL_TIMESTAMP4   TIMESTAMP(2),
  COL_TIMESTAMP5   TIMESTAMP(5),
  COL_TIMESTAMP6   TIMESTAMP(6),
  COL_TIMESTAMP7   TIMESTAMP(6),
  COL_TIMESTAMP8   TIMESTAMP(6),
  COL_TIMESTAMP9   TIMESTAMP(6),
  COL_TIMESTAMP10  TIMESTAMP(6)
,
PRIMARY KEY(COL_NUMBER)
);

