DROP TABLE IF EXISTS sp_pg.QA_TIMESTAMP;

CREATE TABLE sp_pg.QA_TIMESTAMP
(
  COL_NUMBER       NUMBER(25,2),
  COL_TIMESTAMP1   TIMESTAMP(4) WITH TIME ZONE,
  COL_TIMESTAMP2   TIMESTAMP,
  COL_TIMESTAMP3   TIMESTAMP(3) WITH TIME ZONE,
  COL_TIMESTAMP4   TIMESTAMP(2),
  COL_TIMESTAMP5   TIMESTAMP(5) WITH TIME ZONE,
  COL_TIMESTAMP6   TIMESTAMP(6),
  COL_TIMESTAMP7   TIMESTAMP(6) WITH TIME ZONE,
  COL_TIMESTAMP8   TIMESTAMP(6),
  COL_TIMESTAMP9   TIMESTAMP(6) WITH TIME ZONE,
  COL_TIMESTAMP10  TIMESTAMP(6) WITH TIME ZONE
,
PRIMARY KEY(COL_NUMBER)
);

