#!/usr/bin/ksh
export suite_name="ddl_regr_func_based_ind_51_92_nofloat_suite"
export AUTO_SUITE_ID=528
export AUTO_SKIP_SUITE_ORA_8I=1
export AUTO_SRC_SP_USER="sp_ddl_all"
export AUTO_DST_SP_USER="sp_ddl_all"
export sp_user=sp_ddl_all
# Custom driver code below. This is user generated. Default driver not used
#4-10-2014 Julia: skip 12C CR107927
export AUTO_SKIP_SUITE_ORA_12c=1 
./driver $ENV_LIST ddl_regr_fb_conf_list ddl_regr_fb_nofloat_test_list y p
