#!/usr/bin/ksh
export suite_name="disable_lobmap_suite"
export AUTO_SUITE_ID=4714
export AUTO_SKIP_SUITE_ORA_8I=1
export AUTO_SKIP_SUITE_ORA_9I=1
export AUTO_SRC_SP_USER="sp_ddl_all"
export AUTO_DST_SP_USER="sp_ddl_all"
./driver $ENV_LIST disable_lobmap_config_list disable_lobmap_test_list y p