#!/usr/bin/ksh
export suite_name="enable_lobmap_suite"
export AUTO_SUITE_ID=4727
export AUTO_SKIP_SUITE_SPO_VER="9.0"
export AUTO_SRC_SP_USER="sp_ddl_all"
export AUTO_DST_SP_USER="sp_ddl_all"
./driver $ENV_LIST enable_lobmap_config_list enable_lobmap_test_list y p