#!/usr/bin/ksh
export suite_name="set_deferred_segment_creation_suite"
export AUTO_SUITE_ID=1515
export AUTO_SKIP_SUITE_ORA_8I=1
export AUTO_SKIP_SUITE_ORA_9I=1
export AUTO_SKIP_SUITE_ORA_10G=1
export AUTO_SKIP_SUITE_SPO_VER="6.X"
export AUTO_SRC_SP_USER="qarun"
export AUTO_DST_SP_USER="qarun"
export AUTO_SKIP_SUITE_SRC_ORA_GREATER=1
./driver $ENV_LIST set_deferred_segment_creation_conf_list set_deferred_segment_creation_test_list y a