#!/usr/bin/ksh
export suite_name="SPO61_lobcache_sfl_suite"
export AUTO_SUITE_ID=2285
export AUTO_SKIP_SUITE_ORA_8I=1
export AUTO_SKIP_SUITE_SPO_VER="5.X"
export AUTO_SRC_SP_USER="sp_ddl_all"
export AUTO_DST_SP_USER="sp_ddl_all"
./driver $ENV_LIST spo61_lobcache_sfl_conf_list spo61_lobcache_sfl_test_list y p