BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE sp_ssc.MSS_mix
	(
	[key] numeric(18, 0) NOT NULL,
	lower varbinary(500) NULL,
	UPPER varchar(1000) NULL,
	Mix varbinary(4000) NULL,
	TimeStamp timestamp NULL
	)  ON [PRIMARY]
GO
ALTER TABLE sp_ssc.MSS_mix ADD CONSTRAINT
	PK_MSS_mix PRIMARY KEY CLUSTERED 
	(
	[key]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE sp_ssc.MSS_mix SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

