use sp_ss
IF OBJECT_ID('sp_ssc.mss_all_type', 'U') IS NOT NULL
drop table sp_ssc.mss_all_type
go
create table sp_ssc.mss_all_type
(
  COL_NUMBER    numeric not null,
  COL_BIT		BIT,
  COL_TINYINT	TINYINT,
  COL_SMALLINT	SMALLINT,
  COL_INT		INT,
  COL_BIGINT    BIGINT,
  COL_DECIMAL   DECIMAL,
  COL_NUMERIC   NUMERIC,
  COL_REAL      REAL,
  COL_FLOAT	    FLOAT(30),
  COL_TIME	    TIME,
  COL_DATE      DATE,
  COL_SMALLDATETIME   SMALLDATETIME,
  COL_DATETIME  DATETIME,
  COL_DATETIME2 DATETIME2,
  COL_DATETIMEOFFSET  DATETIMEOFFSET,
  COL_CHAR	    CHAR(60),
  COL_VARCHAR   VARCHAR(8000),
  COL_TEXT      TEXT,
  COL_VARCHAR_MAX     VARCHAR(MAX),
  COL_SQL_VARIANT     SQL_VARIANT,
  COL_BINARY	BINARY(120),
  COL_VARBINARY VARBINARY(8000),
  COL_IMAGE     IMAGE,
  COL_VARBINARY_MAX   VARBINARY(MAX),
  COL_NCHAR     NCHAR(30),
  COL_NVARCHAR  NVARCHAR(4000),
  COL_NTEXT     NTEXT,
  COL_NVARCHAR_MAX    NVARCHAR(MAX),
  PRIMARY KEY(COL_NUMBER)
)
go