drop table sp_td.qa_char
go
CREATE TABLE SP_TD.QA_CHAR
( COL_NUMBER  NUMBER(25,2) not null,
  COL_CHAR1   CHAR(100),
  COL_CHAR2   CHAR(500),
  COL_CHAR3   CHAR(1000),
  COL_CHAR4   CHAR(1500),
  COL_CHAR5   CHAR(2000),
CONSTRAINT "PK_QA_CHAR" PRIMARY KEY("COL_NUMBER"))
go
\quit
