drop table sp_td.qa_varchar2
go
CREATE TABLE sp_td.QA_VARCHAR2
 ( COL_NUMBER       NUMBER(25,2) NOT NULL,
  COL_VARCHAR2_1   VARCHAR(100),
  COL_VARCHAR2_2   VARCHAR(500),
  COL_VARCHAR2_3   VARCHAR(1000),
  COL_VARCHAR2_4   VARCHAR(2000),
  COL_VARCHAR2_5   VARCHAR(4000),
CONSTRAINT PK_QA_VARCHAR2 PRIMARY KEY(COL_NUMBER))
go
drop table sp_td.qa_char
go
CREATE TABLE SP_TD.QA_CHAR
( COL_NUMBER  NUMBER(25,2) not null,
  COL_CHAR1   CHAR(100),
  COL_CHAR2   CHAR(500),
  COL_CHAR3   CHAR(1000),
  COL_CHAR4   CHAR(1500),
  COL_CHAR5   CHAR(2000),
CONSTRAINT "PK_QA_CHAR" PRIMARY KEY("COL_NUMBER"))
go
drop table sp_td.QA_DATE_LT1753
go
CREATE TABLE sp_td.QA_DATE_LT1753
(
  COL_NUMBER  NUMBER(25,2) NOT NULL,
  COL_DATE1   timestamp,
  COL_DATE2   timestamp,
  COL_DATE3   timestamp,
  COL_DATE4   timestamp,
  COL_DATE5   timestamp,
CONSTRAINT "PK_QA_DATE_LT1753" PRIMARY KEY("COL_NUMBER"))
go
drop table sp_td.qa_date_gt1753
go
CREATE TABLE sp_td.QA_DATE_GT1753
(
  COL_NUMBER  NUMBER(25,2) NOT NULL,
  COL_DATE1   timestamp,
  COL_DATE2   timestamp,
  COL_DATE3   timestamp,
  COL_DATE4   timestamp,
  COL_DATE5   timestamp,
CONSTRAINT "PK_QA_DATE_GT1753" PRIMARY KEY("COL_NUMBER"))
go
DROP TABLE sp_td.qa_number
go
CREATE TABLE sp_td.QA_NUMBER
(
  COL_NUMBER  NUMBER(26,2) NOT NULL,
  COL_NUMBER1   NUMBER(21,7),
  COL_NUMBER2   NUMBER(25,4),
  COL_NUMBER3   NUMBER(27,2),
  COL_NUMBER4   NUMBER(28,1),
  COL_NUMBER5   NUMBER(29),
CONSTRAINT "PK_QA_NUMBER" PRIMARY KEY("COL_NUMBER"))
go
DROP TABLE sp_td.qa_td_all
go
CREATE TABLE sp_td.QA_TD_ALL
(
ORDER_ID NUMBER NOT NULL,
ORDER_NO VARCHAR(60),
ORDER_PAY NUMBER,
OUGHT_PAY NUMBER,
ACTUAL_PAY NUMBER,
REFUND_PAY NUMBER,
ORDER_STATUS VARCHAR(60),
ORDER_TYPE VARCHAR(60),
PAYMENT_TARGET VARCHAR(60),
PAYMENT_TYPE VARCHAR(60),
PAYMENT_STATUS VARCHAR(60),
ORDER_CHANNEL VARCHAR(60),
ORDER_CHANNEL_NO VARCHAR(60),
BUSINESS_ID NUMBER,
TERMINAL_ID NUMBER,
CREATE_TIME DATE,
CREATE_USER_ID NUMBER,
COMPLETE_TIME DATE,
CANCEL_TIME DATE,
CANCEL_MEMO VARCHAR(300),
SHOPPING_STATUS VARCHAR(60),
MEMO VARCHAR(300),
MEM_ID VARCHAR(60),
STORE_ID VARCHAR(60),
POS_ID VARCHAR(60),
OPERATOR_ID VARCHAR(60),
DISCOUNT_AMOUNT NUMBER,
COUPON_AMOUNT NUMBER,
RECEIPT_AMOUNT NUMBER,
INVOICE_AMOUNT NUMBER,
BUYER_AMOUNT NUMBER,
CONSTRAINT "PK_ORD_ORDER" PRIMARY KEY ("ORDER_ID"))
go
\quit
